ppmb/urls.py
from django.urls import path

from . import views

app_name = 'ppmb'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login, name='login'),
    path('tampil', views.tampil, name='tampil'),
    path('registrasi', views.registrasi_form, name='registrasi-form'),
    path('submit', views.registrasi, name='registrasi'),
]

registrasi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ppmb.urls'))
]

ppmb/models.py
from django.db import models

# Create your models here.

class Fakultas(models.Model):
    nama = models.CharField(max_length=50)
    def __str__(self):
        return self.nama

class Prodi(models.Model):
    """docstring for Prodi."""
    fakultas = models.ForeignKey(
        'Fakultas',
        on_delete=models.CASCADE,
    )
    nama = models.CharField(max_length=50)
    jenjang = models.CharField(max_length=10)
    akreditasi = models.CharField(max_length=2)
    def __str__(self):
        return self.nama

class Pendaftar(models.Model):
    """docstring for ."""
    nik = models.CharField(primary_key=True, max_length=20)
    nama = models.CharField(max_length=50)
    tempat_lahir = models.CharField(max_length=50)
    tanggal_lahir = models.DateField(auto_now=False, auto_now_add=False)
    asal_sekolah = models.CharField(max_length=50)
    jenis_kelamin = models.CharField(max_length=1)
    agama = models.CharField(max_length=15)
    no_seluler = models.CharField(max_length=15)
    tlp_rumah = models.CharField(max_length=15)
    email = models.CharField(max_length=50)
    alamat = models.CharField(max_length=100)
    pilihan1 = models.ForeignKey(
        'Prodi',
        on_delete=models.CASCADE,
        related_name='pilihan1'
    )
    pilihan2 = models.ForeignKey(
        'Prodi',
        on_delete=models.CASCADE,
        related_name='pilihan2'
    )
    pilihan3 = models.ForeignKey(
        'Prodi',
        on_delete=models.CASCADE,
        related_name='pilihan3'
    )
    created_at = models.DateField(auto_now=False, auto_now_add=True)
    updated_at = models.DateField(auto_now=True, auto_now_add=False)
    def __str__(self):
        return self.nama

class User(models.Model):
    email = models.CharField(primary_key=True,max_length=75)
    password = models.CharField(max_length=100)
    remember_token = models.CharField(max_length=100)
    def __str__(self):
        return self.email

ppmb/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import Pendaftar, Prodi
from django.urls import reverse
from django.contrib.auth import authenticate, login

# Create your views here.

def index(request):
    return render(request, 'index.html', {'data': 'data'})

def login(request):
    if not 'email' in request.POST and not 'password' in request.POST:
        return render(request, 'login.html')
    email = request.POST['email']
    password = request.POST['password']
    user = authenticate(request, email=email, password=password)
    if user is not None:
        login(request, user)
        return redirect('ppmb:tampil')
    else:
        return render(request, 'login.html')

def tampil(request):
    if not request.user.is_authenticated:
        return redirect('ppmb:login')
    pendaftar = Pendaftar.objects.all()
    return render(request, 'tampil.html', {'pendaftar': pendaftar})

def registrasi_form(request):
    s1 = Prodi.objects.filter(jenjang='s1').order_by('nama')
    d4 = Prodi.objects.filter(jenjang='d4').order_by('nama')
    d3 = Prodi.objects.filter(jenjang='d3').order_by('nama')
    return render(request, 'registrasi.html', {
    's1': s1, 'd4': d4, 'd3': d3
    })

def registrasi(request):
    data = request.POST
    try:
        pil1 = Prodi.objects.get(pk=data['pil1'])
        pil2 = Prodi.objects.get(pk=data['pil2'])
        pil3 = Prodi.objects.get(pk=data['pil3'])
        pendaftar = Pendaftar(
            nik=data['nik'],
            nama=data['nama'],
            tempat_lahir=data['tempat_lahir'],
            tanggal_lahir=data['tanggal_lahir'],
            asal_sekolah=data['asal_sekolah'],
            jenis_kelamin=data['jenis_kelamin'],
            agama=data['agama'],
            no_seluler=data['no_seluler'],
            tlp_rumah=data['tlp_rumah'],
            email=data['email'],
            alamat=data['alamat'],
            pilihan1=pil1,
            pilihan2=pil2,
            pilihan3=pil3
        )
        pendaftar.save()

    except:
        return HttpResponse('error')
    else:
        return redirect('ppmb:registrasi-form')

ppmb/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'gambar/icon.png' %}">

    <title>Beranda - Pendaftaran Mahasiswa Baru</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand"><a href="" style="text-decoration:none!important">PMB Universitas Airlangga</a></h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="">Beranda</a>
            <a class="nav-link" href="{% url 'ppmb:tampil' %}">Tampil</a>
          </nav>
        </div>
      </header>

      <main role="main" class="inner cover">
        <h1 class="cover-heading">PMB 2018</h1>
        <p class="lead">Selamat datang di website resmi pendaftaran mahasiswa baru jalur mandiri Universitas Airlangga 2018</p>
        <p class="lead">
          <a href="{% url 'ppmb:registrasi-form' %}" class="btn btn-lg"
          style="color:#fff;text-shadow:none;background-color:#c12e3c;border: .05rem solid #c12e3c;">
          Daftar Sekarang</a>
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner text-white">
          <p>
            <a href="http://si.fst.unair.ac.id">S1 Sistem Informasi Universitas Airlangga</a>
            <br>&copy; 2018
          </p>
        </div>
      </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

ppmb/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'gambar/icon.png' %}">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
  </head>

  <body class="text-center">
    <form id="login_form" class="form-signin" method="post">
      {% csrf_token %}
      <a class="mb-4" href="{% url 'ppmb:index' %}">
        <img src="{% static 'gambar/icon.png' %}" alt="" width="72" height="72">
      </a>
      <h1 class="h3 mb-3 font-weight-normal">Masuk</h1>
      <label for="inputEmail" class="sr-only">Email</label>
      <input type="email" id="inputEmail" class="form-control" name="email" placeholder="Alamat email" required autofocus>
      <label for="inputPassword" class="sr-only">Kata Sandi</label>
      <input type="password" id="inputPassword" name="password" class="form-control" placeholder="Kata sandi" required>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" name="simpan" value="remember-me"> Ingat saya
        </label>
      </div>
      <input type="submit" class="btn btn-lg btn-block" value="Masuk"
      style="color:#fff;text-shadow:none;background-color:#c12e3c;border: .05rem solid #c12e3c;">
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>

ppmb/templates/registrasi.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'gambar/icon.png' %}">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/registrasi.css' %}" rel="stylesheet">
    <title>Daftar - Pendaftaran Mahasiswa Baru Universitas Airlangga</title>
  </head>
  <body>
    <div class="row text-white" style="background-color:#c12e3c">
      <div class="container col-md-6 col-sm-12 cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
          <div class="inner">
            <a href="{% url 'ppmb:index' %}">
              <h3 class="masthead-brand">PMB Universitas Airlangga</h3>
            </a>
            <nav class="nav nav-masthead justify-content-center">
              <a class="nav-link" href="{% url 'ppmb:index' %}">Beranda</a>
              <a class="nav-link active" href="#">Registrasi</a>
              <a class="nav-link" href="{% url 'ppmb:tampil' %}">Tampil</a>
            </nav>
          </div>
        </header>
      </div>
    </div>

    <div class="container col-md-6 col-sm-12">
      <form method="post" action="{% url 'ppmb:registrasi' %}">
        {% csrf_token %}

        <div class="containerku my-3 p-3 bg-white rounded box-shadow">
          <h6 class="border-gray pb-2 mb-3" style="border-bottom: 1px solid #c12e3c">Data Diri</h6>

          <div class="form-group row">
            <label for="form_nik" class="col-md-5 col-form-table">NIK</label>
            <div class="col-md-7">
              <input id="form_nik" type="text" class="form-control form-control-sm" placeholder="NIK" name="nik" value="" required>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_nama">Nama</label>
            </div>
            <div class="col-md-7">
              <input id="form_nama" type="text" class="form-control form-control-sm" placeholder="Nama" name="nama" value="" required>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_tempat_lahir">Tempat, tanggal Lahir</label>
            </div>
            <div class="col-md-3">
              <input id="form_tempat_lahir" type="text" class="form-control form-control-sm" placeholder="Tempat Lahir" name="tempat_lahir" value="" required>
            </div>
            <div class="col-md-4">
              <input id="form_tanggal_lahir" type="date" class="form-control form-control-sm" placeholder="Tanggal Lahir" name="tanggal_lahir" value="" required>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_asal_sekolah">Asal Sekolah</label>
            </div>
            <div class="col-md-7">
              <input id="form_asal_sekolah" type="text" class="form-control form-control-sm" placeholder="Asal Sekolah" name="asal_sekolah" value="" required>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_jenis_kelamin">Jenis Kelamin</label>
            </div>
            <div class="col-md-7">
              <select id="form_jenis_kelamin"class="custom-select form-control-sm" name="jenis_kelamin">
                <option selected>Pilih</option>
                <option value="l">Laki-laki</option>
                <option value="p">Perempuan</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_agama">Agama</label>
            </div>
            <div class="col-md-7">
              <select id="form_agama" class="custom-select form-control-sm" name="agama">
                <option selected>Pilih</option>
                <option value="islam">Islam</option>
                <option value="katolik">Katolik</option>
                <option value="katolik">Kristen</option>
                <option value="hindu">Hindu</option>
                <option value="budha">Budha</option>
                <option value="konghucu">Konghucu</option>
              </select>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_seluler">No. Seluler</label>
            </div>
            <div class="col-md-7">
              <div class="input-group">
                <span type="text" class="input-group-text" style="padding: .25rem .5rem;font-size: .875rem;line-height: 1.5;border-radius: .2rem;">+62</span>
                <input type="number" name="no_seluler" class="form-control form-control-sm" id="form_seluler" placeholder="Nomor Seluler" aria-describedby="inputGroupPrepend" required>
              </div>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_tlp_rumah">Telpon Rumah</label>
            </div>
            <div class="col-md-7">
              <div class="input-group">
                <span type="text" class="input-group-text" style="padding: .25rem .5rem;font-size: .875rem;line-height: 1.5;border-radius: .2rem;">0</span>
                <input type="number" name="tlp_rumah" class="form-control form-control-sm" id="form_telp_rumah" placeholder="Nomor Seluler" aria-describedby="inputGroupPrepend" required>
              </div>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_email">Email</label>
            </div>
            <div class="col-md-7">
              <input type="email" name="email" id="form_email" class="form-control form-control-sm" placeholder="Email" value="" required>
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label for="form_alamat">Alamat</label>
            </div>
            <div class="col-md-7">
              <textarea type="text" id="form_alamat" class="form-control form-control-sm" placeholder="Alamat" name="alamat" value="" required></textarea>
            </div>
          </div>
        </div>

        <div class="containerku my-3 p-3 bg-white rounded box-shadow">
          <h6 class="border-gray pb-2 mb-3" style="border-bottom: 1px solid #c12e3c">Pilihan Program Studi</h6>

          <div class="form-group row">
            <div class="col-md-5">
              <label class="pilihan1" for="form_pilihan1">Pilihan Pertama</label>
            </div>
            <div class="col-md-7">
              <input id="form_pilihan1" type="text" placeholder="pilih" class="form-control input-prodi form-control-sm" name="pilihan1" readonly required>
              <input type="hidden" name="pil1" id="pil1" value="">
            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label class="pilihan2" for="form_pilihan2">Pilihan Kedua</label>
            </div>
            <div class="col-md-7">
              <input id="form_pilihan2" type="text" class="form-control input-prodi form-control-sm" name="pilihan2" placeholder="pilih"  readonly required>
              <input type="hidden" name="pil2" id="pil2" value="">

              <div id="master-pilihan" style="display:none">
                <div class="list-group d-flex mt-3" id="list-tab" role="tablist" style="flex-direction:row">
                  <button class="btn btn-sm mr-1 dropdown-toggle" id="list-home-list" data-toggle="list" href="#datas1" role="tab" aria-controls="home">S1</button>
                  <button class="btn btn-sm mr-1 dropdown-toggle" id="list-profile-list" data-toggle="list" href="#datad4" role="tab" aria-controls="profile">D4</button>
                  <button class="btn btn-sm dropdown-toggle" id="list-messages-list" data-toggle="list" href="#datad3" role="tab" aria-controls="messages">D3</button>
                </div>

                <div class="d-flex mt-3">
                  <div class="tab-content" id="nav-tabContent" style="width:100%">

                    <div class="tab-pane fade show" id="datas1" role="tabpanel" aria-labelledby="list-home-list">
                      <div class="list-group">
                        {% for p in s1 %}
                          {% if p.fakultas.id == 16 %}
                          <button type='button' idprodi='{{ p.id }}' class='list-group-item list-group-item-action piljur'>S1 - {{ p.nama }} - PDD Banyuwangi</buton>
                          {% else %}
                          <button type='button' idprodi='{{ p.id }}' class='list-group-item list-group-item-action piljur'>S1 - {{ p.nama }}</buton>
                          {% endif %}
                        {% endfor %}
                      </div>
                    </div>

                    <div class="tab-pane fade" id="datad4" role="tabpanel" aria-labelledby="list-profile-list">
                      <div class="list-group">
                        {% for p in d4 %}
                        <button type='button' idprodi='{{ p.id }}' class='list-group-item list-group-item-action piljur'>D4 - {{ p.nama }}</buton>
                        {% endfor %}
                      </div>
                    </div>

                    <div class="tab-pane fade" id="datad3" role="tabpanel" aria-labelledby="list-messages-list">
                      <div class="list-group">
                        {% for p in d3 %}
                        <button type='button' idprodi='{{ p.id }}' class='list-group-item list-group-item-action piljur'>D3 - {{ p.nama }}</buton>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>
          </div>

          <div class="form-group row">
            <div class="col-md-5">
              <label class="pilihan3" for="form_pilihan3">Pilihan Ketiga</label>
            </div>
            <div class="col-md-7">
              <input id="form_pilihan3" type="text" placeholder="pilih" class="form-control input-prodi form-control-sm" data-toggle="tooltip" data-html="true" title="Anda sudah memilih prodi ini di pilihan ketiga" name="pilihan3" readonly required>
              <input type="hidden" name="pil3" id="pil3" value="">
            </div>
          </div>

        </div>

        <div class="container mb-3">
          <input type="submit" class="btn btn-secondary" value="Daftar"
          style="color:#fff;text-shadow:none;background-color:#c12e3c;border: .05rem solid #c12e3c;">
        </div>

      </form>
    </div>

    <footer class="mastfoot mt-auto">
      <div class="container">
        <div class="inner">
          <p>&copy; 2018 <a href="http://si.fst.unair.ac.id">S1 Sistem Informasi Universitas Airlangga</a></p>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript">
        $('.input-prodi').focus(function(){
            console.log("focus");
            $(this).parent().append($('#master-pilihan'));
            $('#master-pilihan').removeAttr('style');
        });
        $('.input-prodi').focusout(function(){
            console.log('focusout');
        });
        $('.piljur').click(function(){
            var terpilih = $(this).html();
            var input = $(this).closest('.col-md-7').children().first();
            if (!$(this).attr('id')) {
              if ($('#'+input.attr('name')).length !== 0) {
                $('#'+input.attr('name')).removeAttr('id');
              }
              input.val(terpilih);
              var idprodi = $(this).attr('idprodi');
              input.parent().find('input').last().val(idprodi);
              console.log(input.parent().find('input').last());
              $(this).attr('id', input.attr('name'));
              $('#master-pilihan').css("display", "none");
              $('.tab-pane.fade.show.active').attr("class", "tab-pane fade");
              $('.btn.btn-sm.mr-1.dropdown-toggle.active.show').attr("class", "btn btn-sm mr-1 dropdown-toggle").attr("aria-selected", "false");
            } else {
              // var temp = '.' + $(this).attr('id');
              // var option = 'Kamu sudah memilih prodi ini di ' + $(temp).html();
              // console.log(option);
              switch ($(this).attr('id')) {
                case 'pilihan1':
                  $('#form_pilihan1').tooltip('show');
                  break;
                case 'pilihan2':
                  $('#form_pilihan2').tooltip('show');
                  break;
                case 'pilihan3':
                  $('#form_pilihan3').tooltip('show');
                  break;
                default:
                  break;
              }
            }
        });
    </script>
  </body>
</html>

ppmb/templates/tampil.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'gambar/icon.png' %}">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/registrasi.css' %}" rel="stylesheet">

    <link href="{% static 'css/jquery.dataTables.min.css' %}" rel="stylesheet">
    <title>Daftar - Pendaftaran Mahasiswa Baru Universitas Airlangga</title>
  </head>
  <body>
    <div class="row text-white" style="background-color:#c12e3c">
      <div class="container col-md-6 col-sm-12 cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
          <div class="inner">
            <a href="/Registrasi">
              <h3 class="masthead-brand">PMB Universitas Airlangga</h3>
            </a>
            <nav class="nav nav-masthead justify-content-center">
              <a class="nav-link" href="{% url 'ppmb:index' %}">Beranda</a>
              <a class="nav-link" href="{% url 'ppmb:registrasi-form' %}">Registrasi</a>
              <a class="nav-link active" href="{% url 'ppmb:tampil' %}">Tampil</a>
            </nav>
          </div>
        </header>
      </div>
    </div>

    <div class="container col-md-12 col-sm-12">
      <div class="containerku my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-gray pb-2 mb-3" style="border-bottom: 1px solid #c12e3c">Data Pendaftar</h6>
        <div class="form-group row col-md-12" style="font-size:0.875rem" style="width:100%">
          <table id="tabel-ppmb" class="table table-hover table-responsive">
            <thead>
              <tr>
                <th scope="col">NIK</th>
                <th scope="col">Nama</th>
                <th scope="col">Asal Sekolah</th>
                <th scope="col">#</th>
                <th scope="col">No. Seluler</th>
                <th scope="col">Email</th>
                <th scope="col">Agama</th>
                <th scope="col">Alamat</th>
                <th scope="col">Pilihan I</th>
                <th scope="col">Pilihan II</th>
                <th scope="col">Pilihan III</th>
              </tr>
            </thead>
            <tbody>
              {% for p in pendaftar %}
              <tr>
                <td>{{ p.nik }}</td>
                <td>{{ p.nama }}</td>
                <td>{{ p.jenis_kelamin }}</td>
                <td>{{ p.asal_sekolah }}</td>
                <td>{{ p.no_seluler }}</td>
                <td>{{ p.email }}</td>
                <td>{{ p.agama }}</td>
                <td>{{ p.alamat }}</td>
                <td>{{ p.pilihan1 }}</td>
                <td>{{ p.pilihan2 }}</td>
                <td>{{ p.pilihan3 }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <footer class="mastfoot mt-auto">
      <div class="container">
        <div class="inner">
          <p>&copy; 2018 <a href="http://si.fst.unair.ac.id">S1 Sistem Informasi Universitas Airlangga</a></p>
        </div>
      </div>
    </footer>

    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script type="text/javascript">
    $(document).ready( function () {
      $('#tabel-ppmb').DataTable();
    });
    </script>
  </body>
</html>